name: hello_world_desktop
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  csv:

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter